name: bitcoin-tx
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - libexpat=2.6.4
  - libffi=3.4.2
  - liblzma=5.6.4
  - libsqlite=3.48.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.0
  - pip=25.0
  - python=3.11.11
  - readline=8.2
  - setuptools=75.8.0
  - tk=8.6.13
  - tzdata=2025a
  - wheel=0.45.1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.8.0
      - astroid==3.3.8
      - bcrypt==4.2.1
      - click==8.1.8
      - dill==0.3.9
      - ecdsa==0.19.0
      - fastapi==0.115.8
      - h11==0.14.0
      - idna==3.10
      - iniconfig==2.0.0
      - isort==6.0.0
      - markdown-it-py==3.0.0
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mypy==1.15.0
      - mypy-extensions==1.0.0
      - packaging==24.2
      - passlib==1.7.4
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pyasn1==0.6.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pylint==3.3.4
      - pytest==8.3.4
      - python-dotenv==1.0.1
      - python-jose==3.3.0
      - python-multipart==0.0.6
      - rich==13.9.4
      - rsa==4.9
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.37
      - starlette==0.45.3
      - tomlkit==0.13.2
      - typer==0.15.1
      - typing-extensions==4.12.2
      - uvicorn==0.34.0
